### ISSUE TITLE
New icon: Reader Card

### ISSUE THREAD

**Issue by apeatling** [Automattic/gridicons#181]
We'd love to add this icon for previewing what a post will look like in the reader, and other services that offer a card view.

What do we need to do to make this fit the style guidelines?

![19d4e410-639f-11e6-9351-62ecd33fb48a](https://cloud.githubusercontent.com/assets/1464705/17784692/3fd4bfa2-6532-11e6-9093-e68098a56390.png)

**Comment by rickybanister** [comment]
Since these previews are so linked to Publicize and the sharing settings, I feel it'd be much more intuitive to incorporate the sharing icon here. The proposed icon is really similar to the Reader icon and doesn't communicate much about Facebook/Google to me.

**Comment by apeatling** [comment]
The sharing icon was the first idea, but it is confusing since the action of "Sharing" is easily mixed up with publicize. This isn't publicize, and is only really loosely related, so I think we need to be clear with a different icon.

**Comment by rickybanister** [comment]
I agree with that, but replacing a sharing icon with something that looks like the Reader or the Globe or any other icon we already use to represent another idea doesn't seem to be an improvement.

@folletto mentioned trying some ideas that incorporated the sharing icon, but in a 'preview' context. 

Perhaps we could overlay a magnifying glass on top of the existing Reader icon or something like that? Since we'll be previewing in the Reader, it combines and augments both actions?

**Comment by drw158** [comment]
Using the share icon is some way makes the most sense to me, since we are showing what the post looks like after you use Publicize, which uses the share icon. But, we also show the Google preview, so in that way it is related to SEO, which uses the magnifying glass icon.

Ideas:

![screen shot 2016-10-14 at 11 07 37 am](https://cloud.githubusercontent.com/assets/618551/19394354/740ca958-91fe-11e6-9ee4-96bc7e00d3c6.png)

**Comment by folletto** [comment]
In my view it _has_ to include the sharing icon in some way. I really like both your proposal above containing it 👍

**Comment by drw158** [comment]
@folletto Just realized, almost a year later, that we came to the same conclusion, here:

https://github.com/Automattic/wp-calypso/pull/7480#issuecomment-240169577

A desktop icon with the sharing icon inside it. I'll go ahead and make a PR with the icon.

**Comment by folletto** [comment]
I didn't notice either! Way to cross-check our ideas 👯

**Comment by drw158** [comment]
fixed in #222
