### ISSUE TITLE
New icon: Nametag

### ISSUE THREAD

**Issue by mapk** [Automattic/gridicons#236]
I'd like to create a new icon indicating a name of something. 

<img width="576" alt="grid" src="https://user-images.githubusercontent.com/617986/28128529-e09e0e48-66e4-11e7-945b-2946ebc82957.png">

For example, using it in a possible NUX flow here:

![nux-flow](https://user-images.githubusercontent.com/617986/28128615-2d2abc02-66e5-11e7-9af9-2e6846a92c93.png)

With other icons:
<img width="541" alt="inline-with-others" src="https://user-images.githubusercontent.com/617986/28128271-076d9be8-66e4-11e7-8baa-8216be231df8.png">

**Comment by mapk** [comment]
Not sure if the clip part of the icon is done correctly. Please advise. It's off the grid, but keeping correct width and radii.

**Comment by drw158** [comment]
Looks like a good idea to me. Do you mind opening a PR with the svg file added to the sources/svg folder? I'd like to look at the file.

**Comment by mapk** [comment]
PR created here: https://github.com/Automattic/gridicons/pull/237

**Comment by drw158** [comment]
I try to not overlay solid shapes with white strokes, because usually there is a tendency to use a 1px stroke and make the icon looks less solid or too detailed. Do any of these alternate designs on the right look good to you?

Same 3 icons shown at different resolutions

![screen shot 2017-07-12 at 12 26 01 pm](https://user-images.githubusercontent.com/618551/28130780-87393bac-66fd-11e7-996f-407d589804a8.png)
![screen shot 2017-07-12 at 12 25 53 pm](https://user-images.githubusercontent.com/618551/28130781-8746134a-66fd-11e7-866e-87891160e08a.png)
![screen shot 2017-07-12 at 12 25 42 pm](https://user-images.githubusercontent.com/618551/28130782-874893a4-66fd-11e7-8e38-680db6b894ae.png)

**Comment by mapk** [comment]
OK @drw158, keeping the conversation here on the ticket, I do like this one that you created here. That's probably my favorite so far!
![alternate](https://user-images.githubusercontent.com/617986/28143219-613a8ec6-6719-11e7-9fa5-dafe2739efae.png)

The only other idea I had was this, which is moved over from the PR thread.
![option-3](https://user-images.githubusercontent.com/617986/28143249-7097578c-6719-11e7-80d6-d327e3a6615a.png)

**Comment by mapk** [comment]
@drw158 would you like me to update the PR with the one you created?

**Comment by drw158** [comment]
I think this one might be my favorite, but fine with either one:

![screen shot 2017-07-12 at 7 00 03 pm](https://user-images.githubusercontent.com/618551/28144962-61520c0c-6734-11e7-9ea9-4437f7c72120.png)

The 1px white stroke I think is my main concern with your idea. We try to minimize 1px strokes as much as we can. And, if the stroke is 2px it seems like it's too big, and too much negative space.

**Comment by mapk** [comment]
Let's go with that one. I do like the added weight of the top black bar to signify the 'name badge' feeling. Would you like me to update the PR?

**Comment by drw158** [comment]
Sure, thank you for working with me!

**Comment by mapk** [comment]
Awesome! I've updated the PR with the new icon. Please review and let me know if there's anything else I can do to help here. :)

**Comment by drw158** [comment]
Done! #239
