### ISSUE TITLE
New Icon: WooCommerce

### ISSUE THREAD

**Issue by jameskoster** [Automattic/gridicons#292]
We're using Gridicons in the wc-admin project we're currently working on and have a need for a Woo bubble icon. Is that the sort of thing that makes sense to add to Gridicons? If so I'll open a PR, if not we'll work something else out :)

@folletto @drw158

**Comment by folletto** [comment]
If it's a logo, it's usually better suited for https://github.com/Automattic/social-logos :) 

Note that the "W" is instead in Gridicons because it has been tweaked (weight, size, balance) to be aligned with the Gridicons standard, so it's not anymore exactlu "the logo", and that's why it's also named "my sites".

**Comment by jameskoster** [comment]
Yeah I thought as much, but it's a little grey as the Jetpack logo is in there as well.

I'll wait for more consensus, the icon is ready to go either way.

**Comment by folletto** [comment]
> Yeah I thought as much, but it's a little grey as the Jetpack logo is in there as well.

Similar to "My Sites", that's not Jetpack but "Plans" :)

**Comment by jameskoster** [comment]
Yeah I don't think there's any meaning. 

Let's add to Social Icons.
