### ISSUE TITLE
Add Icon: Image caption

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/gridicons#82]
In the editor, you can add a caption to an image from the inline image toolbar. Right now we are using the `comment` icon, which isn't very intuitive:

<img width="648" alt="screen shot 2015-08-21 at 4 21 24 pm" src="https://cloud.githubusercontent.com/assets/5835847/9419364/b250c63c-4820-11e5-9166-3f384f1404ad.png">

**Comment by afsheenirani** [comment]
+1 to "Another idea" since it looks most like captioning as opposed to commenting. 

It would be awesome if that same icon would depict something that looked like an image in the whitespace above the caption so it would read as image captioning...essentially a partial of what `<Gridicon icon="image" />` gives you.

**Comment by drw158** [comment]
Refining that idea

![screen shot 2016-03-03 at 4 19 29 pm](https://cloud.githubusercontent.com/assets/618551/13511898/f0364622-e15c-11e5-866a-2b29636f882e.png)

**Comment by kellychoffman** [comment]
Nice. 

Do you think it looks too much like the New Post icon?

**Comment by folletto** [comment]
It's similar... true. I wonder if they will be ever used one on the side of the other so they can give in some confusion. :)

Maybe it's still ok. I'm wondering if there's enough space to have the image "above" and the caption written by the pencil "below" instead of inside. That might make it even more clear.

**Comment by afsheenirani** [comment]
For consistency with all image icons, we should probably use this as the image to which the caption is being added using the pencil. Thoughts?

![image](https://cloud.githubusercontent.com/assets/14303849/13544850/022aaace-e24a-11e5-9574-2ed2649ad176.png)

**Comment by kellychoffman** [comment]
@folletto True, I don't think the icon @drw158 suggested would ever be misconstrued as Add New Post because of its placement.

@afsheenirani  I think adding an image to the pencil would make it seem like you were editing the image itself.

**Comment by drw158** [comment]
@afsheenirani I like the idea of using the landscape image, I'll try that out.

**Comment by drw158** [comment]
Latest:

![screen shot 2016-03-17 at 11 11 18 am](https://cloud.githubusercontent.com/assets/618551/13852650/0a9c5446-ec31-11e5-931e-a90c43079115.png)
![screen shot 2016-03-17 at 11 10 55 am](https://cloud.githubusercontent.com/assets/618551/13852654/0d3bf620-ec31-11e5-85c2-9a9fbf4ab20f.png)

**Comment by folletto** [comment]
I'd +1 that. :) 
:shipit:

**Comment by afsheenirani** [comment]
Nice...I would simply call this a "caption" icon...it is generic to be
applied to any use-case requiring captions i.e., images, figures, graphs,
etc.
