### ISSUE TITLE
Add script to generate `npm` package that can be used in Calypso

### ISSUE THREAD

**Issue by gcorne** [Automattic/gridicons#98]

**Comment by afsheenirani** [comment]
@retrofox, @jasmussen @gcorne - I think this is a great idea and I've been taking a look into it. I will submit a PR soon to kick-off discussions on the design based on a first draft that I've built. 

However, at a high level, to answer @retrofox's question...the way I'm envisioning it to work is that once you install and import the gridicons package into calypso, all you would need to do to display an icon should be:

`gridicons( 'iconName', iconSize, iconOnClickHandler )`

A call to the above function would end up returning the required `<svg></svg>` tag which can be easily embedded into any React components `render()` function. Given this, we may need to do away with the `Gridicons` React class in calypso (but that is a second step once we have a publicly available working npm gridicons package).

Here's what i think should be made available in the published npm package:

1. The index.js module which provides the `gridicons` function.
2. A LICSENSE.md file
3. A Readme.md file
4. Examples - This is something I would like to get a broader view on. Do we want to keep the examples + search of gridicons in the calypso project or should we just redirect this to the gridicons repo from calypso? My view is Calypso should redirect to the gridicons repo since the gridicons repo should be a wholistic project in itself.

In addition to what will be published we will need a few things for the generation and management of the npm package:

1. Updates to Gruntfile.js to generate the index.js module
2. A mechanism to test the generated index.js module locally on client side before publishing to npm.
 - I'm currently using Browserify to bundle up all `require` related node dependencies like `classnames` and expose this on the client side for testing. Do let me know if there are better ways to achieve this and I can explore that.
3. A shell script or Readme.md set of instructions on how to publish the npm package for newer releases.
 - Maintaining versioning of releases

cc: @folletto @drw158 @kellychoffman @nb  as well.

**Comment by gwwar** [comment]
Should be resolved by #188
